### ISSUE TITLE
Import - debug-import

### ISSUE THREAD

**Issue by Danielprobst22** [nordic-dev-net/hydrophonitor-cli#15]
Add --debug-import option to the import command
This option should copy the deployment data from the device directly as it is, conserving the original structure of the sub-directories and without merging any files.

**Comment by Danielprobst22** [comment]
@juliuskoskela @satukoskinen Is this option for the import command still relevant or is it taken care of by the separate debug command https://github.com/nordic-dev-net/hydrophonitor-cli/issues/12

**Comment by juliuskoskela** [comment]
> @juliuskoskela @satukoskinen Is this option for the import command still relevant or is it taken care of by the separate debug command #12

Separate debug command imo

**Comment by satukoskinen** [comment]
We can use the separate debug command instead. I forgot to remove the mention of `--debug-import` flag when the separate debug command was added.
